name: citizenwallet
description: A new Dart package that provides shared app logic
version: 0.0.2
homepage: https://github.com/citizenwallet/dart-sdk

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:

dev_dependencies:
  test: ^1.24.0
  lints: ^2.1.0
